config/routes.rb
MeshesOfCinema::Application.routes.draw do
  resources :movements
  resources :genres
  resources :directors
  resources :mini_reviews

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admins
  
  resources :films

  match "/reviews", to: 'reviews#index'
  match "/articles", to: 'articles#index'
  match "/admin", to: 'admin#index'
  match "/mini_articles", to: 'mini_articles#index'
  match "/themes", to: 'themes#index'
  match "/elements", to: 'elements#index'
  match "/countries", to: 'countries#index'
  match "/tags", to: 'tags#index'
  match "/directors", to: 'directors#index'
  match "/about", to: 'standard#about'
  match "/contact", to: 'standard#contact'
  root to: 'standard#index'

  match "/search/films", to: 'films#search'

end

app/models/movement.rb
# == Schema Information
#
# Table name: movements
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Movement < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  # GET /movements
  # GET /movements.json
  def index
    @movements = Movement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movements }
    end
  end

  # GET /movements/1
  # GET /movements/1.json
  def show
    @movement = Movement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movement }
    end
  end

  # GET /movements/new
  # GET /movements/new.json
  def new
    @movement = Movement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movement }
    end
  end

  # GET /movements/1/edit
  def edit
    @movement = Movement.find(params[:id])
  end

  # POST /movements
  # POST /movements.json
  def create
    @movement = Movement.new(params[:movement])

    respond_to do |format|
      if @movement.save
        format.html { redirect_to @movement, notice: 'Movement was successfully created.' }
        format.json { render json: @movement, status: :created, location: @movement }
      else
        format.html { render action: "new" }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movements/1
  # PUT /movements/1.json
  def update
    @movement = Movement.find(params[:id])

    respond_to do |format|
      if @movement.update_attributes(params[:movement])
        format.html { redirect_to @movement, notice: 'Movement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movements/1
  # DELETE /movements/1.json
  def destroy
    @movement = Movement.find(params[:id])
    @movement.destroy

    respond_to do |format|
      format.html { redirect_to movements_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/views/movements/_form.html.haml
= form_for @movement do |f|
  -if @movement.errors.any?
    #error_explanation
      %h2= "#{pluralize(@movement.errors.count, "error")} prohibited this movement from being saved:"
      %ul
        - @movement.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/movements/edit.html.haml
%h1 Editing movement

= render 'form'

= link_to 'Show', @movement
\|
= link_to 'Back', movements_path

app/views/movements/index.html.haml
%h1 Listing movements

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @movements.each do |movement|
    %tr
      %td= movement.name
      %td= link_to 'Show', movement
      %td= link_to 'Edit', edit_movement_path(movement)
      %td= link_to 'Destroy', movement, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Movement', new_movement_path

app/views/movements/new.html.haml
%h1 New movement

= render 'form'

= link_to 'Back', movements_path

app/views/movements/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @movement.name

= link_to 'Edit', edit_movement_path(@movement)
\|
= link_to 'Back', movements_path