config/routes.rb
MeshesOfCinema::Application.routes.draw do
  resources :movements
  resources :genres
  resources :directors
  resources :mini_reviews

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admins
  
  resources :films

  match "/reviews", to: 'reviews#index'
  match "/articles", to: 'articles#index'
  match "/admin", to: 'admin#index'
  match "/mini_articles", to: 'mini_articles#index'
  match "/themes", to: 'themes#index'
  match "/elements", to: 'elements#index'
  match "/countries", to: 'countries#index'
  match "/tags", to: 'tags#index'
  match "/directors", to: 'directors#index'
  match "/about", to: 'standard#about'
  match "/contact", to: 'standard#contact'
  root to: 'standard#index'

  match "/search/films", to: 'films#search'

end

app/models/element.rb
# == Schema Information
#
# Table name: elements
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Element < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :films
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  # GET /elements
  # GET /elements.json
  def index
    @elements = Element.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @elements }
    end
  end

  # GET /elements/1
  # GET /elements/1.json
  def show
    @element = Element.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @element }
    end
  end

  # GET /elements/new
  # GET /elements/new.json
  def new
    @element = Element.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @element }
    end
  end

  # GET /elements/1/edit
  def edit
    @element = Element.find(params[:id])
  end

  # POST /elements
  # POST /elements.json
  def create
    @element = Element.new(params[:element])

    respond_to do |format|
      if @element.save
        format.html { redirect_to @element, notice: 'Element was successfully created.' }
        format.json { render json: @element, status: :created, location: @element }
      else
        format.html { render action: "new" }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /elements/1
  # PUT /elements/1.json
  def update
    @element = Element.find(params[:id])

    respond_to do |format|
      if @element.update_attributes(params[:element])
        format.html { redirect_to @element, notice: 'Element was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.json
  def destroy
    @element = Element.find(params[:id])
    @element.destroy

    respond_to do |format|
      format.html { redirect_to elements_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/views/elements/_form.html.erb
<%= form_for(@element) do |f| %>
  <% if @element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
      <% @element.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/elements/_form.html.haml
= form_for(@element) do |f|
  - if @element.errors.any?
    #error_explanation
      %h2
        = pluralize(@element.errors.count, "error")
        prohibited this element from being saved:
      %ul
        - @element.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/elements/edit.html.erb
<h1>Editing element</h1>

<%= render 'form' %>

<%= link_to 'Show', @element %> |
<%= link_to 'Back', elements_path %>

app/views/elements/edit.html.haml
%h1 Editing element
= render 'form'
= link_to 'Show', @element
|
\#{link_to 'Back', elements_path}

app/views/elements/index.html.erb
<h1>Listing elements</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @elements.each do |element| %>
  <tr>
    <td><%= element.name %></td>
    <td><%= link_to 'Show', element %></td>
    <td><%= link_to 'Edit', edit_element_path(element) %></td>
    <td><%= link_to 'Destroy', element, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/elements/index.html.haml
%h1 Listing elements
%table
  %tr
    %th Name
    %th
    %th
    %th
  - @elements.each do |element|
    %tr
      %td= element.name
      %td= link_to 'Show', element
      %td= link_to 'Edit', edit_element_path(element)
      %td= link_to 'Destroy', element, method: :delete, data: { confirm: 'Are you sure?' }
%br/

app/views/elements/new.html.erb
<h1>New element</h1>

<%= render 'form' %>

<%= link_to 'Back', elements_path %>

app/views/elements/new.html.haml
%h1 New element
= render 'form'
= link_to 'Back', elements_path

app/views/elements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @element.name %>
</p>


<%= link_to 'Edit', edit_element_path(@element) %> |
<%= link_to 'Back', elements_path %>

app/views/elements/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @element.name
= link_to 'Edit', edit_element_path(@element)
|
\#{link_to 'Back', elements_path}