config/routes.rb
MeshesOfCinema::Application.routes.draw do
  resources :movements
  resources :genres
  resources :directors
  resources :mini_reviews

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admins
  
  resources :films

  match "/reviews", to: 'reviews#index'
  match "/articles", to: 'articles#index'
  match "/admin", to: 'admin#index'
  match "/mini_articles", to: 'mini_articles#index'
  match "/themes", to: 'themes#index'
  match "/elements", to: 'elements#index'
  match "/countries", to: 'countries#index'
  match "/tags", to: 'tags#index'
  match "/directors", to: 'directors#index'
  match "/about", to: 'standard#about'
  match "/contact", to: 'standard#contact'
  root to: 'standard#index'

  match "/search/films", to: 'films#search'

end

app/models/film.rb
# == Schema Information
#
# Table name: films
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  year       :integer
#  imdb_id    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Film < ActiveRecord::Base
  attr_accessible :name, :year, :imdb_id, :director_ids, :genre_ids
  has_and_belongs_to_many :directors
  has_and_belongs_to_many :elements
  has_and_belongs_to_many :articles
  has_and_belongs_to_many :genres
  has_and_belongs_to_many :movements
  has_and_belongs_to_many :themes
  has_and_belongs_to_many :mini_reviews
  has_and_belongs_to_many :reviews
  acts_as_taggable_on :tags

  #searchable do
  #  text :name
  #end

  def formatted_name
    "#{name} (#{year})"
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_filter :authenticate_admin!, except: [:index, :show]

  # GET /films
  # GET /films.json
  def index
    @films = Film.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @films }
    end
  end

  # GET /films/1
  # GET /films/1.json
  def show
    @film = Film.find_by_id(params[:id]) || Film.find_by_imdb_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @film }
    end
  end

  # GET /films/new
  # GET /films/new.json
  def new
    @film = Film.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @film }
    end
  end

  # GET /films/1/edit
  def edit
    @film = Film.find_by_id(params[:id]) || Film.find_by_imdb_id(params[:id])
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(params[:film])

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render json: @film, status: :created, location: @film }
      else
        format.html { render action: "new" }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /films/1
  # PUT /films/1.json
  def update
    @film = Film.find_by_id(params[:id]) || Film.find_by_imdb_id(params[:id])

    respond_to do |format|
      if @film.update_attributes(params[:film])
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film = Film.find_by_id(params[:id]) || Film.find_by_imdb_id(params[:id])
    @film.destroy

    respond_to do |format|
      format.html { redirect_to films_url }
      format.json { head :no_content }
    end
  end

  def search
    @search = Film.search do
      fulltext params[:search]
    end
    @films = @search.results
    
    respond_to do |format|
      format.html # search.html.erb
      format.json { render json: @films }
    end
  end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.haml
= semantic_form_for(@film) do |f|
  - if @film.errors.any?
    #error_explanation
      %h2
        = pluralize(@film.errors.count, "error")
        prohibited this film from being saved:
      %ul
        - @film.errors.full_messages.each do |msg|
          %li= msg

  = f.inputs do
    = f.input :name
    = f.input :year
    = f.input :imdb_id
    = f.input :directors
    = f.input :genres
  = f.actions

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render 'form' %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/edit.html.haml
%h1 Editing film
= render 'form'
= link_to 'Show', @film
|
\#{link_to 'Back', films_path}

app/views/films/index.html.erb
<h1>Listing films</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @films.each do |film| %>
  <tr>
    <td><%= film.name %></td>
    <td><%= film.year %></td>
    <td><%= link_to 'Show', film %></td>
    <td><%= link_to 'Edit', edit_film_path(film) %></td>
    <td><%= link_to 'Destroy', film, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/films/index.html.haml
%h1 Listing films
%table
  %tr
    %th Name
    %th Rating
    %th
    %th
    %th
  - @films.each do |film|
    %tr
      %td= film.name
      %td= film.year
      %td= link_to 'Show', film
      %td= link_to 'Edit', edit_film_path(film)
      %td= link_to 'Destroy', film, method: :delete, data: { confirm: 'Are you sure?' }
%br/

app/views/films/new.html.erb
<h1>New film</h1>

<%= render 'form' %>

<%= link_to 'Back', films_path %>

app/views/films/new.html.haml
%h1 New film
= render 'form'
= link_to 'Back', films_path

app/views/films/search.html.haml
%h1 Listing films

%table
  %tr
    %th Name
    %th Rating
    %th/
    %th/
    %th/

- @films.each do |film|
  %tr
    %td= film.name
    %td= film.year
    %td= link_to 'Show', film
    %td= link_to 'Edit', edit_film_path(film)
    %td= link_to 'Destroy', film, method: :delete, data: { confirm: 'Are you sure?' }


%br/

app/views/films/show.html.haml
%p#notice= notice

%h2= @film.formatted_name
%p
  Directed by:
  = (@film.directors.all.map {|d| link_to d.name, "/directors/#{d.id}"}).to_sentence.html_safe