config/routes.rb
MeshesOfCinema::Application.routes.draw do
  resources :movements
  resources :genres
  resources :directors
  resources :mini_reviews

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admins
  
  resources :films

  match "/reviews", to: 'reviews#index'
  match "/articles", to: 'articles#index'
  match "/admin", to: 'admin#index'
  match "/mini_articles", to: 'mini_articles#index'
  match "/themes", to: 'themes#index'
  match "/elements", to: 'elements#index'
  match "/countries", to: 'countries#index'
  match "/tags", to: 'tags#index'
  match "/directors", to: 'directors#index'
  match "/about", to: 'standard#about'
  match "/contact", to: 'standard#contact'
  root to: 'standard#index'

  match "/search/films", to: 'films#search'

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id   :integer          not null, primary key
#  name :string(255)
#

class Tag < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :films
  has_and_belongs_to_many :directors
  has_and_belongs_to_many :mini_articles
  has_and_belongs_to_many :articles
  has_and_belongs_to_many :mini_reviews
  has_and_belongs_to_many :reviews
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/_form.html.haml
= form_for(@tag) do |f|
  - if @tag.errors.any?
    #error_explanation
      %h2
        = pluralize(@tag.errors.count, "error")
        prohibited this tag from being saved:
      %ul
        - @tag.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/edit.html.haml
%h1 Editing tag
= render 'form'
= link_to 'Show', @tag
|
\#{link_to 'Back', tags_path}

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.name %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/tags/index.html.haml
%h1 Listing tags
%table
  %tr
    %th Name
    %th
    %th
    %th
  - @tags.each do |tag|
    %tr
      %td= tag.name
      %td= link_to 'Show', tag
      %td= link_to 'Edit', edit_tag_path(tag)
      %td= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' }
%br/

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/new.html.haml
%h1 New tag
= render 'form'
= link_to 'Back', tags_path

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tag.name %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/tags/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @tag.name
= link_to 'Edit', edit_tag_path(@tag)
|
\#{link_to 'Back', tags_path}